### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by vjpr** [taskcluster/gdb-js#1]
I'm running `gdb` child process like:

```
arm-none-eabi-gdb-py \
  --i=mi \
  main
```

I'm doing something like this connecting to a gdbserver running in qemu.

```
await this.gdb.init()
await this.gdb.execMI(`-target-select remote ${host}:${port}`)
await this.gdb.execMI(`-file-exec-and-symbols ${file}`)
await this.gdb.execMI('-target-download')
```

CLI commands work fine, but this doesn't.

I'm getting the following error. I am printing from the childProcess.stdout and stderr too.

```
gdb stdout: ~"<gdbjs:event:new-objfile /Users/Vaughan/dev-quantitec/intranav-firmware/bin/qemu-cpputest/Intranav.elf new-objfile:event:gdbjs>"

gdb stdout: ^done
(gdb)

stdout: Write  776 bytes at 0x08000000-0x08000307.
stdout: Write   12 bytes at 0x08000308-0x08000313.
gdb stdout: +download,{section=".isr_vector",section-size="776",total-size="1308713"}
+download,{section=".inits",section-size="12",total-size="1308713"}


/Users/Vaughan/dev-live/dimsim/node_modules/.store/gdb-js@1.1.1/_/lib/webpack:/src/parsers/gdbmi.pegjs:1371
          if (!arr[i].name) arr[i].name = arr[i - 1].name
^
TypeError: Cannot read property 'name' of undefined
    at makeResults (/Users/Vaughan/dev-live/dimsim/node_modules/.store/gdb-js@1.1.1/_/lib/webpack:/src/parsers/gdbmi.pegjs:1371:1)
    at peg$c26 (/Users/Vaughan/dev-live/dimsim/node_modules/.store/gdb-js@1.1.1/_/lib/webpack:/src/parsers/gdbmi.pegjs:74:23)
    at peg$parseAsyncOutput (/Users/Vaughan/dev-live/dimsim/node_modules/.store/gdb-js@1.1.1/_/lib/webpack:/src/parsers/gdbmi.pegjs:670:1)
    at peg$parseStatusAsyncOutput (/Users/Vaughan/dev-live/dimsim/node_modules/.store/gdb-js@1.1.1/_/lib/webpack:/src/parsers/gdbmi.pegjs:515:1)
    at peg$parseAsyncRecord (/Users/Vaughan/dev-live/dimsim/node_modules/.store/gdb-js@1.1.1/_/lib/webpack:/src/parsers/gdbmi.pegjs:393:1)
    at peg$parseLine (/Users/Vaughan/dev-live/dimsim/node_modules/.store/gdb-js@1.1.1/_/lib/webpack:/src/parsers/gdbmi.pegjs:336:1)
    at peg$parse (/Users/Vaughan/dev-live/dimsim/node_modules/.store/gdb-js@1.1.1/_/lib/webpack:/src/parsers/gdbmi.pegjs:1388:1)
    at /Users/Vaughan/dev-live/dimsim/node_modules/.store/highland@2.10.0/_/lib/index.js:1949:25
    at Stream.s._send (/Users/Vaughan/dev-live/dimsim/node_modules/.store/highland@2.10.0/_/lib/index.js:1448:9)
    at Stream.write (/Users/Vaughan/dev-live/dimsim/node_modules/.store/highland@2.10.0/_/lib/index.js:1548:18)
    at Stream._send (/Users/Vaughan/dev-live/dimsim/node_modules/.store/highland@2.10.0/_/lib/index.js:912:26)
    at push (/Users/Vaughan/dev-live/dimsim/node_modules/.store/highland@2.10.0/_/lib/index.js:1413:19)
    at /Users/Vaughan/dev-live/dimsim/node_modules/.store/highland@2.10.0/_/lib/index.js:1954:13
    at Stream.s._send (/Users/Vaughan/dev-live/dimsim/node_modules/.store/highland@2.10.0/_/lib/index.js:1448:9)
    at Stream.write (/Users/Vaughan/dev-live/dimsim/node_modules/.store/highland@2.10.0/_/lib/index.js:1548:18)
    at Stream._send (/Users/Vaughan/dev-live/dimsim/node_modules/.store/highland@2.10.0/_/lib/index.js:912:26)
```

**Comment by vjpr** [comment]
Looks like the bug is here:

```
    for (let i = 0; i < arr.length; i++) {
      if (!arr[i].name) arr[i].name = arr[i - 1].name
    }
```

With input: 

```
+download,{section=".isr_vector",section-size="776",total-size="1308713"}
```

```
    // when i = 0
    // console.log('ARR:', arr)
    for (let i = 0; i < arr.length; i++) {
      if (!arr[0].name) arr[0].name = arr[0 - 1].name
    }
```

```
ARR: [ { name: 'section', value: '.isr_vector' },
  { name: 'section-size', value: '776' },
  { name: 'total-size', value: '1308711' } ]
ARR: [ { name: null,
    value:
     { section: '.isr_vector',
       'section-size': '776',
       'total-size': '1308711' } } ]
```

This seems to fix it, but not sure whats going on here.

```
if (!arr[i].name && i !== 0) arr[i].name = arr[i - 1].name
```

**Comment by baygeldin** [comment]
@vjpr thanks for the info. The problem is indeed in GDB/MI grammar parser, or more specifically in [GDB/MI output grammar](https://sourceware.org/gdb/onlinedocs/gdb/GDB_002fMI-Output-Syntax.html) itself. Every result of output syntax should have a name. In this case in could have been like this:

```
+download,info={section=".isr_vector",section-size="776",total-size="1308713"}
```

and the parsed JSON would have looked like this:

``` json
{
   "type": "status",
   "state": "download",
   "data": {
      "info": {
         "section": ".isr_vector",
         "section-size": "776",
         "total-size": "1308713"
      }
   }
}
```

But since the record doesn't have any name it causes an error. IMO, this solution is pretty fine:

``` javascript
for (let i = 0; i < arr.length; i++) {
  if (!arr[i].name) arr[i].name = arr[i - 1] ? arr[i - 1].name : "unnamed"
}
```

It gathers all records without a name under one record called "unnamed". 

I'll try to push this change in a couple of days and see if doesn't break anything (I'm sure it's okay though). Or you could submit a PR 😉

**Comment by baygeldin** [comment]
1.1.2 released, sorry that it took so long.
