### ISSUE TITLE
var-create parse problem

### ISSUE THREAD

**Issue by gil-n** [taskcluster/gdb-js#4]
hi, 

Trying to run the following command  execMI("-var-create v1 * argc") fails with parsing error.

**this is the result:**
x = "^done,name="v1",numchild="0",value="1",type="int",thread-id="1",has_more="0""

**stack:**
"SyntaxError: Expected "=", "[", "[]", "{", "{}" or c-string but "_" found.
    at peg$buildException (node_modules\gdb-js\lib\index.js:2883:15)
    at peg$parse (node_modules\gdb-js\lib\index.js:3955:14)
    **at node_modules\highland\lib\index.js:1998:25**
    at Stream.consume.s._send (node_modules\highland\lib\index.js:1485:9)
    at Stream.write (node_modules\highland\lib\index.js:1585:18)
    at Stream._send (node_modules\highland\lib\index.js:923:26)
    at Stream.consume.push (node_modules\highland\lib\index.js:1452:19)
    at node_modules\highland\lib\index.js:2003:13
    at Stream.consume.s._send (node_modules\highland\lib\index.js:1485:9)
    at Stream.write (node_modules\highland\lib\index.js:1585:18)"

**it looks like gdbmi parser fails on the 'has_more' attribute.**
when i intercept the result and replace has_more with hasmore it works.

Any thoughts?

**Comment by gil-n** [comment]
meanwhile...;) found the problem
in gdbmi.pegjs the String rule needs to include an underscore, like so:

String "string"
  = [a-z-**_**]+ { return text() }

can you update please?

**Comment by baygeldin** [comment]
Yet another bug with GDB/MI output syntax... Thanks for pointing this out :)
Fixed by c1f0bf15d8b7caab0f5b94f465731b59203ecb62. 1.1.4 released.
